### ISSUE TITLE
Any screenshots?

### ISSUE THREAD

**Issue by dynoChris** [lucasvegi/PokemonGoCloneOffline#3]

**Comment by lucasvegi** [comment]
Hello @vadimTovstik, thanks for asking!

Your question motivated me to finally create a [README](https://github.com/lucasvegi/PokemonGoCloneOffline/blob/master/README.md) that values the project. I just updated it by adding screenshots, a demonstration video, and the app documentation. I hope you enjoy it!

**Comment by dynoChris** [comment]
> Hello @vadimTovstik, thanks for asking!
> 
> Your question motivated me to finally create a [README](https://github.com/lucasvegi/PokemonGoCloneOffline/blob/master/README.md) that values the project. I just updated it by adding screenshots, a demonstration video, and the app documentation. I hope you enjoy it!

Oh, many thanks. It's so cool now! 😮
